<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <StartupObject>Xpand.Events.Examples.RunAll</StartupObject>
        <Authors>Nikolay Nakorkeshko</Authors>
        <LangVersion>9</LangVersion>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Xpand.Events\Xpand.Events.csproj" />
    </ItemGroup>
    
</Project>
