<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\SignalSmokeProgram.cs" Link="Program.cs" />
        <ProjectReference Include="..\..\Xpand.Events.Core\Xpand.Events.Core.csproj" />
    </ItemGroup>

</Project>
